### ISSUE TITLE
Problems Encountered

### ISSUE THREAD

**Issue by Osgood001** [yuzh2001/zhineng_exp#2]
下载完毕，可以·python inference.py`直接运行了，现在进入debug时间

首先遇到的是

```sh
TypeError: Unpickler.__init__() got an unexpected keyword argument 'mmap'
```

参考 https://github.com/ggerganov/llama.cpp/issues/4319 解决了，注释掉了`mmap`。

```py

    def load_weights(self, model_path: str):
        self.load_state_dict(
            torch.load(
                model_path, 
                # mmap=True, 
                weights_only=True,
            )['model_state_dict'],
            strict=False,
        )
```
（已修改）

然后是不支持ComplexFloat的 Index_select_mlu

```sh
RuntimeError: "index_select_mlu" not implemented for 'ComplexFloat'
```

1. 尝试转换为float类型
```py

    @torch.no_grad()
    def forward(
        self,
        input_token_ids: torch.Tensor,
        input_positions: torch.Tensor,
        kv_write_indices: torch.Tensor,
        kv_caches: List[Tuple[torch.Tensor, torch.Tensor]],
        mask: torch.Tensor,
        output_positions: torch.Tensor,
        temperatures: Union[torch.Tensor, None],
        top_ps: torch.Tensor,
        top_ks: torch.Tensor,
        **kwargs,
    ) -> torch.Tensor:
    # Modified to convert to float from complex
        freqs_cis = self.freqs_cis.float()
        freqs_cis = freqs_cis.index_select(0, input_positions)
        kv_write_indices = input_positions

```
结果

```sh
RuntimeError: CNNL cast currently do not support complex type
```

查询开发者手册，此处cast是数据转换，暂不支持complex 2 float，而且这个显然不是一个好的转换，会损失虚部。

### 为什么会出现这个问题？

在某处，函数使用complex datatype来进行读取和运算。

参考[知乎回答](https://zhuanlan.zhihu.com/p/684113260)，此处的freqs_cis是一个计算位置编码 Position embedding的函数。

```py
def precompute_freqs_cis(dim: int,
                         end: int,
                         theta: float = 10000.0) -> torch.Tensor:
    """Precomputes the frequency cis."""
    freqs = 1.0 / (theta**(torch.arange(0, dim, 2)[:(dim // 2)].float() / dim))
    t = torch.arange(end, device=freqs.device)
    freqs = torch.outer(t, freqs).float()
    freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    return freqs_cis
```

出现了`#complex64`，很合理吧，那么，CNNL居然不支持complex number 的运算？我不是很认可。

直接的解决方案：实现CNNL的复数算子

按照这篇知乎文章的说法，大多数模型使用positional embedding的模型应该都会遇到这个困难，不过做llama3的小伙伴说没有遇到，所以，考虑做出来（参考作业），或者换个模型（看看远处的llama系列） @yuzh2001

**Comment by yuzh2001** [comment]
```python
        freqs_cis = []
        for idx in input_positions:
            freqs_cis.append(self.freqs_cis[idx])
        # freqs_cis = self.freqs_cis.index_select(0, input_positions)
```
手写后这段代码可以正常运行了，但是后面的又出问题了。

```bash
[2024-5-7 11:48:22] [CNNL] [Error]:[cnnlTransform] The bfloat16 data type supports only MLU590, 1V, or higher.
[ERROR][/torch/catch/torch_mlu/csrc/aten/operators/cnnl/internal/transform_internal.cpp:68][operator()][process:8811][thread:139670961559360]: 
Traceback (most recent call last):
  File "/workspace/algorithm/transfer/zhineng_exp/inference.py", line 55, in <module>
    result = model.generate(
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 523, in generate
    next_token_ids = self(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 437, in forward
    hidden_states = hidden_states * (self.config.hidden_size**0.5)
RuntimeError: CNNL error: CNNL_STATUS_NOT_SUPPORTED
```

貌似是卡（370）不行。。

**Comment by yuzh2001** [comment]
change dtype to float solves.

**Comment by yuzh2001** [comment]
```bash
/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py:501: UserWarning:  MLU operators don't support 64-bit calculation. so the 64 bit data will be forcibly converted to 32-bit for calculation.  (Triggered internally at /torch/catch/torch_mlu/csrc/aten/utils/tensor_util.cpp:159.)
  token_ids_tensor = token_ids_tensor.to(device)
Traceback (most recent call last):
  File "/workspace/algorithm/transfer/zhineng_exp/inference.py", line 56, in <module>
    result = model.generate(
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 522, in generate
    next_token_ids = self(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 438, in forward
    hidden_states = self.model(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 376, in forward
    hidden_states = layer(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 336, in forward
    hidden_states = self.self_attn(
  File "/torch/venv3/pytorch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 262, in forward
    xq = apply_rotary_emb(xq, freqs_cis=freqs_cis)
  File "/workspace/algorithm/transfer/zhineng_exp/gemma_pytorch/gemma/model.py", line 101, in apply_rotary_emb
    x_out = torch.view_as_real(x_ * freqs_cis).type_as(x)
TypeError: only integer tensors of a single element can be converted to an index
```
